# Generated by Django 5.2.7 on 2025-11-02 15:21

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                (
                    "serial_number",
                    models.CharField(
                        default=core.models.generate_serial, max_length=200, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_genuine", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_serial", models.CharField(blank=True, max_length=200)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                (
                    "evidence_image",
                    models.ImageField(blank=True, null=True, upload_to="reports/"),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
